### ISSUE TITLE
Why when start date and end date set as empty creates warnings in run-time?

### ISSUE THREAD

**Issue by oshiniG** [snamoah/react-datetime-range-picker#13]
Once we set initially  start Date and end Date yo empty it will creates some warning .

import React, { Component } from "react";
import DatetimeRangePicker from 'react-datetime-range-picker';

class Test extends Component {
      <DatetimeRangePicker
       startDate= {""}
       endDate={""}
       input = {true}
       timeFormat="HH:mm"
       dateFormat="DD/MM/YY"
        inputProps={{ placeholder: ('Enter Date')}} />
}

![777](https://user-images.githubusercontent.com/49180691/55609389-79a41800-5778-11e9-8342-c4d47b3f8975.png)

@snamoah do you have any idea ?

**Comment by snamoah** [comment]
@oshiniG startDate and endDate take either a date object or moment object as values... you're passing a string

**Comment by oshiniG** [comment]
@snamoah ok thanks. initially  i want to set dates as empty . as you said date object (new Date()) will represent datetime now. Once i set 'moment(null)' set value empty but still error is there. I want to set start and end date as empty.

**Comment by snamoah** [comment]
oh ok.. currently, that is not possible... you need to set an initial date value. can you submit a PR with a fix? otherwise, I'll submit the fix in a later version

**Comment by oshiniG** [comment]
Thanks a lot. when do you plan to release the later version?

**Comment by oshiniG** [comment]
> oh ok.. currently, that is not possible... you need to set an initial date value. can you submit a PR with a fix? otherwise, I'll submit the fix in a later version

Hi is there any update from your side?

**Comment by snamoah** [comment]
@oshiniG just published an update [v2.0.5](https://www.npmjs.com/package/react-datetime-range-picker) with a fix. Added string as part of the propTypes for end date and start date

**Comment by snamoah** [comment]
closing issue
