### ISSUE TITLE
Can't disable selection of future dates

### ISSUE THREAD

**Issue by danieltapp** [snamoah/react-datetime-range-picker#16]
I don't want the user to be able to select dates beyond the current date. I tried setting the isValidDate property with the following to no avail...

const today = Datetime.moment()
const valid =  current => !current.isAfter( today );

<DatetimeRangePicker isValidDate={valid} />

**Comment by snamoah** [comment]
@danieltapp there's no option for `isValidDate` in this package... you have to set this on `isValidEndDate` instead. hope this helps

**Comment by danieltapp** [comment]
That did the trick! Much appreciated.

**Comment by snamoah** [comment]
you're welcome... closing issue
