### ISSUE TITLE
Is it possible to have inputs be inline versus stacked?

### ISSUE THREAD

**Issue by danieltapp** [snamoah/react-datetime-range-picker#17]
By default they appear to be stacked, but I'd like the inputs to be inline. I tried applying Bootstrap classes for inline and/or block display to pickerClassName to no avail. Is there a prop that can be utilized so the individual inputs sit inline next to one another?

**Comment by snamoah** [comment]
if you're using bootstrap, you can have something like this

```javascript
<DatetimeRangePicker
    className="row"
    pickerClassName="col-xs-6"
/>
```
